# Generated by Django 2.0.5 on 2018-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
