# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20180822_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ImageField(default='/static/images/default.jpg', max_length=200, upload_to='authors/%Y/%m/', verbose_name='作者图片'),
        ),
    ]
