# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('organization', '0003_auto_20180814_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='机构课程'),
        ),
    ]
