# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course',
        ),
    ]
