# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='讲师年龄'),
        ),
    ]
