# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180817_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='视频链接'),
        ),
    ]
