# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_needknow',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_clue',
            field=models.CharField(default='', max_length=100, verbose_name='讲师提示'),
        ),
    ]
