# Generated by Django 2.0.5 on 2018-06-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='del_pass',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
