# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteChech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField()),
                ('pollid', models.PositiveIntegerField()),
                ('vote_date', models.DateField()),
            ],
        ),
    ]
