# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20180822_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='小说简介'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='详细介绍'),
        ),
    ]
