# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20180822_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='site_name',
            field=models.CharField(max_length=32, verbose_name='小说网站'),
        ),
    ]
