# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20180822_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/default.jpg', max_length=200, null=True, upload_to='novel/%Y/%m/', verbose_name='小说图片'),
        ),
    ]
