# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20180824_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter0',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter1',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter2',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter3',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter4',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter5',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter6',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter7',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter8',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='chapter9',
            name='chapter_index',
            field=models.PositiveIntegerField(default=0, verbose_name='章节顺序'),
        ),
    ]
